Prep
deepjyoti30/ytmdl pull request #213
Opened 2022-01-24 23:03 UTC by HeavyTony2

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/deepjyoti30/ytmdl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [ytmdl coding conventions](https://github.com/deepjyoti30/ytmdl/blob/master/.github/CONTRIBUTING.md) and adjusted the code to meet them
- [ ] Checked the code with [pylama](https://github.com/klen/pylama)
- [ ] Made the pull request to the **unstable** branch

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

2022-01-30 10:01 UTC, deepjyoti30 requested changes

2022-01-30 10:01 UTC, deepjyoti30 commented on setup.py
> +    ('etc/bash_completion.d', 'ytmdl.bash'),
@HeavyTony2 Can't we do this change just for windows systems using the check `name == 'nt'`? It seems like removing the `/` will result in issues in *nix systems.

Did you happen to test this PR on any *nix based system?

2022-01-30 10:01 UTC, deepjyoti30 commented on setup.py
> +    'beautifulsoup4',
Why is this change necessary?

2022-01-30 15:43 UTC, HeavyTony2 commented on setup.py
> +    'beautifulsoup4',
Here's the result without the patch (https://github.com/conda-forge/ytmdl-feedstock/blob/master/recipe/setup.py.patch)

```
  ERROR: Could not find a version that satisfies the requirement bs4 (from versions: none)
  ERROR: No matching distribution found for bs4
```
As silly it may looks, there are a cases like that where Conda-Build is very sensitive. I mean, it will install the BS4 package, but it won't recognize it as such.

2022-01-30 16:44 UTC, HeavyTony2 commented on setup.py
> +    ('etc/bash_completion.d', 'ytmdl.bash'),
Yes. I also did the test by install ytmdl throug pip and throug conda. It seems to work normally. Your idea might be safer thougt.

2022-01-30 16:49 UTC, deepjyoti30 commented on setup.py
> +    'beautifulsoup4',
Okay, I see. I will have to cross check to make sure this doesn't break current pip support in other OS'es. Though I think `bs4` and `beautifulsoup4` resolve to be the same library in `pip`?

2022-01-30 16:50 UTC, deepjyoti30 commented on setup.py
> +    ('etc/bash_completion.d', 'ytmdl.bash'),
Yeah, I think it's better to keep these changes just for Windows since that is what the use case is. Making them universal might have some unseen side effects.

2022-01-30 21:20 UTC, HeavyTony2 commented on setup.py
> +    'beautifulsoup4',
This is right. However, it translates weird for Conda-Build. A similar case is with sklearn/scikit-learn.

2022-02-02 05:15 UTC, deepjyoti30 commented on setup.py
> +    'beautifulsoup4',
@HeavyTony2 But we should be able to get rid of this error depending on the OS version in the `setup.py` file right?

2022-02-02 13:48 UTC, HeavyTony2 commented on setup.py
> +    'beautifulsoup4',
Not for that one, on both Windows and Linux, there are this error with bsr/beautifulsoup4

2022-06-19 12:37 UTC, closed without merging